In [3]:
import pandas as pd

#CROSS TABULATION

df=pd.read_csv('auto-mpg.csv')
pd.crosstab(df['cylinders'],df['model year'],rownames=['cylinders'],colnames=['model year'])

model year  70  71  72  73  74  75  76  77  78  79  80  81  82
cylinders
3            0   0   1   1   0   0   0   1   0   0   1   0   0
4            7  13  14  11  15  12  15  14  17  12  25  21  28
5            0   0   0   0   0   0   0   0   1   1   1   0   0
6            4   8   0   8   7  12  10   5  12   6   2   7   3
8           18   7  13  20   5   6   9   8   6  10   0   1   0

In [ ]:
# Data cleaning 
#missing value
# 1 delete complete row with NaN .it will delete all the data of row

In [4]:
import numpy as np
sales_data=pd.DataFrame({'name':['willam','Emma','sofia','markus','Anika','paul','Edward','Thomus','Ethan',np.nan,'Arun',np.nan],
                         'region':[np.nan,'North','East',np.nan,'west','west','south',np.nan,'west','east','south',np.nan],
                        'sales':[50000,52000,np.nan,np.nan,42000,72000,49000,np.nan,67000,65000,67000,np.nan],
                        'exponses':[42000,43000,np.nan,np.nan,38000,39000,42000,np.nan,39000,50000,45000,np.nan]})
sales_data

      name region    sales  exponses
0   willam    NaN  50000.0   42000.0
1     Emma  North  52000.0   43000.0
2    sofia   East      NaN       NaN
3   markus    NaN      NaN       NaN
4    Anika   west  42000.0   38000.0
5     paul   west  72000.0   39000.0
6   Edward  south  49000.0   42000.0
7   Thomus    NaN      NaN       NaN
8    Ethan   west  67000.0   39000.0
9      NaN   east  65000.0   50000.0
10    Arun  south  67000.0   45000.0
11     NaN    NaN      NaN       NaN

In [5]:
sales_data.isna().sum()

name        1
region      3
sales       3
exponses    3
dtype: int64

In [6]:
sales_data.dropna()

      name region    sales  exponses
1     Emma  North  52000.0   43000.0
4    Anika   west  42000.0   38000.0
5     paul   west  72000.0   39000.0
6   Edward  south  49000.0   42000.0
8    Ethan   west  67000.0   39000.0
10    Arun  south  67000.0   45000.0

In [10]:
sales_data.dropna(thresh=1)

      name region    sales  exponses
0   willam    NaN  50000.0   42000.0
1     Emma  North  52000.0   43000.0
2    sofia   East      NaN       NaN
3   markus    NaN      NaN       NaN
4    Anika   west  42000.0   38000.0
5     paul   west  72000.0   39000.0
6   Edward  south  49000.0   42000.0
7   Thomus    NaN      NaN       NaN
8    Ethan   west  67000.0   39000.0
9      NaN   east  65000.0   50000.0
10    Arun  south  67000.0   45000.0

In [7]:
sales_data.dropna(thresh=2)

      name region    sales  exponses
0   willam    NaN  50000.0   42000.0
1     Emma  North  52000.0   43000.0
2    sofia   East      NaN       NaN
4    Anika   west  42000.0   38000.0
5     paul   west  72000.0   39000.0
6   Edward  south  49000.0   42000.0
8    Ethan   west  67000.0   39000.0
9      NaN   east  65000.0   50000.0
10    Arun  south  67000.0   45000.0

In [8]:
sales_data.dropna(thresh=3)

      name region    sales  exponses
0   willam    NaN  50000.0   42000.0
1     Emma  North  52000.0   43000.0
4    Anika   west  42000.0   38000.0
5     paul   west  72000.0   39000.0
6   Edward  south  49000.0   42000.0
8    Ethan   west  67000.0   39000.0
9      NaN   east  65000.0   50000.0
10    Arun  south  67000.0   45000.0

In [9]:
sales_data.dropna(thresh=4)
# jo 4 hoy to 4 valid data hova joye em

      name region    sales  exponses
1     Emma  North  52000.0   43000.0
4    Anika   west  42000.0   38000.0
5     paul   west  72000.0   39000.0
6   Edward  south  49000.0   42000.0
8    Ethan   west  67000.0   39000.0
10    Arun  south  67000.0   45000.0

In [14]:
sales_data.dropna(how='all')

      name region    sales  exponses
0   willam    NaN  50000.0   42000.0
1     Emma  North  52000.0   43000.0
2    sofia   East      NaN       NaN
3   markus    NaN      NaN       NaN
4    Anika   west  42000.0   38000.0
5     paul   west  72000.0   39000.0
6   Edward  south  49000.0   42000.0
7   Thomus    NaN      NaN       NaN
8    Ethan   west  67000.0   39000.0
9      NaN   east  65000.0   50000.0
10    Arun  south  67000.0   45000.0

In [15]:
sales_data.dropna(how='any')

      name region    sales  exponses
1     Emma  North  52000.0   43000.0
4    Anika   west  42000.0   38000.0
5     paul   west  72000.0   39000.0
6   Edward  south  49000.0   42000.0
8    Ethan   west  67000.0   39000.0
10    Arun  south  67000.0   45000.0

In [17]:
sales_data.dropna(subset=['sales','exponses'])

      name region    sales  exponses
0   willam    NaN  50000.0   42000.0
1     Emma  North  52000.0   43000.0
4    Anika   west  42000.0   38000.0
5     paul   west  72000.0   39000.0
6   Edward  south  49000.0   42000.0
8    Ethan   west  67000.0   39000.0
9      NaN   east  65000.0   50000.0
10    Arun  south  67000.0   45000.0

In [19]:
sales_data.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [23]:
sales_data.dropna(inplace=True)
sales_data

      name region    sales  exponses
1     Emma  North  52000.0   43000.0
4    Anika   west  42000.0   38000.0
5     paul   west  72000.0   39000.0
6   Edward  south  49000.0   42000.0
8    Ethan   west  67000.0   39000.0
10    Arun  south  67000.0   45000.0

In [25]:
# fill with dummy data
sales_data.fillna(0)

      name region    sales  exponses
0   willam      0  50000.0   42000.0
1     Emma  North  52000.0   43000.0
2    sofia   East      0.0       0.0
3   markus      0      0.0       0.0
4    Anika   west  42000.0   38000.0
5     paul   west  72000.0   39000.0
6   Edward  south  49000.0   42000.0
7   Thomus      0      0.0       0.0
8    Ethan   west  67000.0   39000.0
9        0   east  65000.0   50000.0
10    Arun  south  67000.0   45000.0
11       0      0      0.0       0.0

In [37]:
# repalce it with mean,median values
sales_data['sales'].fillna({'sales':sales_data['sales'].mean()},inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_16224\574836470.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sales_data['sales'].fillna({'sales':sales_data['sales'].mean()},inplace=True)

In [31]:
sales_data['sales']=sales_data['exponses'].fillna(sales_data['exponses'].median())

In [32]:
sales_data

      name region    sales  exponses
0   willam    NaN  42000.0   42000.0
1     Emma  North  43000.0   43000.0
2    sofia   East  42000.0       NaN
3   markus    NaN  42000.0       NaN
4    Anika   west  38000.0   38000.0
5     paul   west  39000.0   39000.0
6   Edward  south  42000.0   42000.0
7   Thomus    NaN  42000.0       NaN
8    Ethan   west  39000.0   39000.0
9      NaN   east  50000.0   50000.0
10    Arun  south  45000.0   45000.0
11     NaN    NaN  42000.0       NaN

In [40]:
df=df[df['horsepower']!='?']
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [18]:
df=df[df['horsepower']=='?']
df

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 32 to 374
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           6 non-null      float64
 1   cylinders     6 non-null      int64
 2   displacement  6 non-null      float64
 3   horsepower    6 non-null      object
 4   weight        6 non-null      int64
 5   acceleration  6 non-null      float64
 6   model year    6 non-null      int64
 7   origin        6 non-null      int64
 8   car name      6 non-null      object
dtypes: float64(3), int64(4), object(2)
memory usage: 480.0+ bytes

In [7]:
df.drop('mpg',axis=1)

,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...
393,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,4,97.0,52,2130,24.6,82,2,vw pickup
395,4,135.0,84,2295,11.6,82,1,dodge rampage
396,4,120.0,79,2625,18.6,82,1,ford ranger
397,4,119.0,82,2720,19.4,82,1,chevy s-10

In [14]:
def find_outliers(ds,col):
    q1=ds[col].quantile(0.25)
    q3=ds[col].quantile(0.75)
    iqr=q3-q1
    low_value=q1-1.5*iqr
    high_value=q3+1.5*iqr
    print(low_value)
    print(high_value)
    ds=ds.loc[(ds[col]<low_value)|(ds[col]>high_value)]
    return ds

df=pd.read_csv('auto-mpg.csv')
find_outliers(df,'mpg')

0.25
46.25

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
322,46.6,4,86.0,65,2110,17.9,80,3,mazda glc

In [15]:
find_outliers(df,'acceleration')

8.8
22.2

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
7,14.0,8,440.0,215,4312,8.5,70,1,plymouth fury iii
9,15.0,8,390.0,190,3850,8.5,70,1,amc ambassador dpl
11,14.0,8,340.0,160,3609,8.0,70,1,plymouth 'cuda 340
59,23.0,4,97.0,54,2254,23.5,72,2,volkswagen type 3
299,27.2,4,141.0,71,3190,24.8,79,2,peugeot 504
326,43.4,4,90.0,48,2335,23.7,80,2,vw dasher (diesel)
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup

In [16]:
def remove_outliers(ds,col):
    q1=ds[col].quantile(0.25)
    q3=ds[col].quantile(0.75)
    iqr=q3-q1
    low_value=q1-1.5*iqr
    high_value=q3+1.5*iqr
    print(low_value)
    print(high_value)
    ds=ds.loc[(ds[col]>=low_value)&(ds[col]<=high_value)]
    return ds

df=pd.read_csv('auto-mpg.csv')
remove_outliers(df,'mpg')

0.25
46.25

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 32 to 374
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           6 non-null      float64
 1   cylinders     6 non-null      int64
 2   displacement  6 non-null      float64
 3   horsepower    6 non-null      object
 4   weight        6 non-null      int64
 5   acceleration  6 non-null      float64
 6   model year    6 non-null      int64
 7   origin        6 non-null      int64
 8   car name      6 non-null      object
dtypes: float64(3), int64(4), object(2)
memory usage: 480.0+ bytes

In [24]:
df['horsepower']=df['horsepower'].astype('int64')
df.info()

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'method'