In [2]:
import pandas as pd
data={'A':["TeamA","TeamB","TeamB","TeamC","TeamA"],
     "B":[50,40,40,30,50],
     "C":[True,False,False,False,True]}
df=pd.DataFrame(data)
df

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
2  TeamB  40  False
3  TeamC  30  False
4  TeamA  50   True

In [5]:
df.duplicated()

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [6]:
df.duplicated(keep='first')

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [7]:
df.duplicated(keep='last')

0     True
1     True
2    False
3    False
4    False
dtype: bool

In [9]:
df.duplicated(keep=False)

0     True
1     True
2     True
3    False
4     True
dtype: bool

In [3]:
df.drop_duplicates()

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
3  TeamC  30  False

In [5]:
df.drop_duplicates(keep="first")

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
3  TeamC  30  False

In [6]:
df.drop_duplicates(keep="last")

       A   B      C
2  TeamB  40  False
3  TeamC  30  False
4  TeamA  50   True

In [7]:
df.drop_duplicates(keep=False)

       A   B      C
3  TeamC  30  False

In [10]:
df.drop_duplicates(keep="first",inplace=True)

In [11]:
df.reset_index(drop=True)

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
2  TeamC  30  False

In [12]:
import pandas as pd
df=pd.read_csv('auto-mpg.csv')
pd.crosstab(df['cylinders'],df['model year'],rownames=['cylinders'],colnames=['model year'])

model year  70  71  72  73  74  75  76  77  78  79  80  81  82
cylinders
3            0   0   1   1   0   0   0   1   0   0   1   0   0
4            7  13  14  11  15  12  15  14  17  12  25  21  28
5            0   0   0   0   0   0   0   0   1   1   1   0   0
6            4   8   0   8   7  12  10   5  12   6   2   7   3
8           18   7  13  20   5   6   9   8   6  10   0   1   0

In [22]:
data={'Name':['Alice',"Bob","Charlie","David"],
     'Score':[88,92,95,90]}
df=pd.DataFrame(data)
df

      Name  Score
0    Alice     88
1      Bob     92
2  Charlie     95
3    David     90

In [14]:
sorted_df=df.sort_values(by='Score')
sorted_df

      Name  Score
0    Alice     88
3    David     90
1      Bob     92
2  Charlie     95

In [15]:
sorted_df=df.sort_values(by='Name')
sorted_df

      Name  Score
0    Alice     88
1      Bob     92
2  Charlie     95
3    David     90

In [17]:
sorted_df=df.sort_values(by='Score',ascending=False)
sorted_df

      Name  Score
2  Charlie     95
1      Bob     92
3    David     90
0    Alice     88

In [18]:
df.sort_index(ascending=False)

      Name  Score
3    David     90
2  Charlie     95
1      Bob     92
0    Alice     88

In [23]:
df.set_index('Name',inplace=True)
df

         Score
Name
Alice       88
Bob         92
Charlie     95
David       90

In [25]:
df.sort_index(ascending=False,inplace=True)
df

         Score
Name
David       90
Charlie     95
Bob         92
Alice       88

In [27]:
s=pd.Series([35,67,90,45])
def pass_fail(x):
    return "pass" if x>=50 else "fail"
result=s.apply(pass_fail)
print(result)

0    fail
1    pass
2    pass
3    fail
dtype: object

In [30]:
df1=pd.DataFrame({
    "physics":[60,70,80],
    "chemistry":[65,75,85],
    "maths":[70,80,90]
})
df1

   physics  chemistry  maths
0       60         65     70
1       70         75     80
2       80         85     90

In [31]:
result=df1.apply(sum)
print(result)

physics      210
chemistry    225
maths        240
dtype: int64

In [32]:
result=df1.apply(sum,axis=1)
print(result)

0    195
1    225
2    255
dtype: int64

In [34]:
# using lamda
result=df1.apply(lambda x:x.mean())
print(result)

physics      70.0
chemistry    75.0
maths        80.0
dtype: float64

In [36]:
df1

   physics  chemistry  maths
0       60         65     70
1       70         75     80
2       80         85     90

In [40]:
df1['total']=df1.apply(lambda x:x.sum(),axis=1)
df1

   physics  chemistry  maths  total
0       60         65     70  195.0
1       70         75     80  225.0
2       80         85     90  255.0

In [47]:
def grade(total):
    if total>=250:
        return 'A'
    elif total>=200:
        return "B"
    else:
        return "C"
df1['Grade']=df1['total'].apply(grade)
df1

   physics  chemistry  maths  total Grade
0       60         65     70  195.0     C
1       70         75     80  225.0     B
2       80         85     90  255.0     A

In [51]:
df2=pd.DataFrame({'width':[1,2],'height':[3,4]})
def get_stats(row):
    return [row['width']*row['height'],2*(row['width']+row['height'])]
df2

   width  height
0      1       3
1      2       4

In [53]:
df2.apply(get_stats,axis=1)

0     [3, 8]
1    [8, 12]
dtype: object

In [52]:
df2.apply(get_stats,axis=1,result_type='expand')

   0   1
0  3   8
1  8  12

In [54]:
df2.apply(get_stats,axis=1,result_type='reduce')

0     [3, 8]
1    [8, 12]
dtype: object

In [56]:
df2.apply(get_stats,axis=1,result_type='broadcast')

   width  height
0      3       8
1      8      12

In [60]:
def add_values(x,y,z):
    return x+y+z
df4=pd.DataFrame({'A':[1,2],"B":[10,20]}) 
df5=df4.apply(add_values,args=(1,2))
print(df5)

   A   B
0  4  13
1  5  23

In [61]:
df=pd.DataFrame({
    'a':['1','2','3'],
    'b':['4','5','6']
})
print(df.dtypes)

a    object
b    object
dtype: object

In [62]:
df['a']=df['a'].astype(int)
print(df.dtypes)

a     int64
b    object
dtype: object

In [65]:
df1=pd.DataFrame({
    'marks':[80,85,0,90],
    'attendance':[75,80,0,85],
    'Grade':['A','B','F','A']
})
print(df1)

print()
result=df1.replace(0,60)
print(result)

   marks  attendance Grade
0     80          75     A
1     85          80     B
2      0           0     F
3     90          85     A

   marks  attendance Grade
0     80          75     A
1     85          80     B
2     60          60     F
3     90          85     A

In [68]:
df1=pd.DataFrame({
    'marks':[80,85,0,90],
    'attendance':[75,80,0,85],
    'Grade':['A','B','F','A']
})
print(df1)

print()
result1=df1.replace([80,75],[90,80])
print(result1)

   marks  attendance Grade
0     80          75     A
1     85          80     B
2      0           0     F
3     90          85     A

   marks  attendance Grade
0     90          80     A
1     85          90     B
2      0           0     F
3     90          85     A

In [77]:
df1=pd.DataFrame({
    'marks':[80,85,0,90],
    'attendance':[75,80,0,85],
    'Grade':['A','B','F','A']
})
print(df1)

print()
result2=df1.replace({80:90,85:80})
print(result2)

   marks  attendance Grade
0     80          75     A
1     85          80     B
2      0           0     F
3     90          85     A

   marks  attendance Grade
0     90          75     A
1     80          90     B
2      0           0     F
3     90          80     A

In [72]:
df1['marks']=df1['marks'].replace(0,50)
df1

   marks  attendance Grade
0     80          75     A
1     85          80     B
2     50           0     F
3     90          85     A

In [75]:
df1['attendance']=df1['attendance'].replace(0,60)
df1

   marks  attendance Grade
0     80          75     A
1     85          80     B
2     50          50     F
3     90          85     A

In [88]:
df1=pd.DataFrame({'a':['1','2'],'b':['10','20']})
df2=pd.DataFrame({'a':['11','12'],'c':['100','200']})
result=pd.concat([df1,df2],axis=1)
result

   a   b   a    c
0  1  10  11  100
1  2  20  12  200

In [86]:
df1=pd.DataFrame({'a':['1','2'],'b':['10','20']})
df2=pd.DataFrame({'a':['11','12'],'c':['100','200']})
result=pd.concat([df1,df2])
result

    a    b    c
0   1   10  NaN
1   2   20  NaN
0  11  NaN  100
1  12  NaN  200

In [87]:
pd.concat([df1,df2],join='outer')

    a    b    c
0   1   10  NaN
1   2   20  NaN
0  11  NaN  100
1  12  NaN  200

In [81]:
pd.concat([df1,df2], join='inner')

    a    b
0   1   10
1   2   20
0  11  100
1  12  200

In [83]:
pd.concat([df1,df2], join='inner',ignore_index=True)

    a    b
0   1   10
1   2   20
2  11  100
3  12  200

In [92]:
df1=pd.DataFrame({
    'e':[9,10],
    'b':[3,4]
})
df2=pd.DataFrame({
    'c':[5,6],
    'd':[7,8]
})
pd.concat([df1,df2],sort=True)

     b    c    d     e
0  3.0  NaN  NaN   9.0
1  4.0  NaN  NaN  10.0
0  NaN  5.0  7.0   NaN
1  NaN  6.0  8.0   NaN

In [93]:
pd.concat([df1,df2],sort=False,axis=1)

    e  b  c  d
0   9  3  5  7
1  10  4  6  8

In [94]:
pd.concat([df1,df2],sort=True,axis=1)

    e  b  c  d
0   9  3  5  7
1  10  4  6  8

In [97]:
df1=pd.DataFrame({
    'employee':['a','b','c'],
    'department':['it','hr','finance']
})
df2=pd.DataFrame({
    'employee':['a','b','d'],
    'salary':[50000,40000,30000]

})
r1=pd.merge(df1,df2,on='employee',how='inner')
print(r1)

  employee department  salary
0        a         it   50000
1        b         hr   40000

In [98]:
r1=pd.merge(df1,df2,on='employee',how='outer')
print(r1)

  employee department   salary
0        a         it  50000.0
1        b         hr  40000.0
2        c    finance      NaN
3        d        NaN  30000.0

In [99]:
r1=pd.merge(df1,df2,on='employee',how='left')
print(r1)

  employee department   salary
0        a         it  50000.0
1        b         hr  40000.0
2        c    finance      NaN

In [100]:
r1=pd.merge(df1,df2,on='employee',how='right')
print(r1)

  employee department  salary
0        a         it   50000
1        b         hr   40000
2        d        NaN   30000